#!/usr/bin/env python3
"""Disable obsolete vanilla events without breaking direct event references.

The generated override files retain every vanilla event ID as a hidden no-op.
This is safer than empty files because vanilla on-actions and scripted systems
directly invoke many historical event IDs.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "MillenniumDawnEU4"
EVENT_OUTPUT = MOD / "events"
DISASTER_OUTPUT = MOD / "common" / "disasters"
LOCALISATION_OUTPUT = MOD / "localisation" / "eu4_2k_disabled_vanilla_events_l_english.yml"
MARKER = "# Generated by scripts/disable_obsolete_vanilla_events.py"
LOCALISATION_TEXT = """l_english:
 eu4_2k_disabled_event_title:0 "Obsolete Historical Event"
 eu4_2k_disabled_event_desc:0 "This historical event is not used by the modern scenario."
 eu4_2k_disabled_event_option:0 "Continue"
"""

GAME_CANDIDATES = (
    Path(r"F:\Steam\steamapps\common\Europa Universalis IV"),
    Path(r"C:\Program Files (x86)\Steam\steamapps\common\Europa Universalis IV"),
    Path(r"C:\Program Files\Steam\steamapps\common\Europa Universalis IV"),
)

CATEGORY_REASONS = {
    "country_flavor": "obsolete medieval or early-modern country flavor",
    "mission_content": "event content belonging to removed vanilla missions",
    "historical_disaster": "obsolete historical or early-modern disaster",
    "religious_wars": "Reformation or European religious-war history",
    "colonial_history": "historical colonization or colonial-nation content",
    "hre_history": "Holy Roman Empire history or imperial incidents",
    "dynastic_history": "early-modern dynastic or personal-union history",
    "revolution_history": "vanilla eighteenth- or nineteenth-century revolution content",
    "obsolete_system": "obsolete ruler, conquest, institution, or state-system content",
}

# Generic Civil War, Internal Conflicts, and estate disasters remain available.
KEEP_DISASTER_EVENT_FILES = {
    "disaster_civilwar.txt",
    "disaster_internalconflicts.txt",
    "disaster_estates.txt",
}

RELIGIOUS_WAR_FILES = {
    "europeanleagues.txt",
    "interconfessionalwars.txt",
    "protestantism.txt",
    "religiousleagues.txt",
    "tywevents.txt",
    "westphalia.txt",
}

COLONIAL_FILES = {
    "americanrevolution.txt",
    "colonial.txt",
    "coloniallife.txt",
    "colonialnation.txt",
    "discoveryofthefareast.txt",
    "explorationevents.txt",
    "indiantradecompany.txt",
    "minorityexpulsionevents.txt",
    "native_federation_events.txt",
    "nativeamerican.txt",
    "natives.txt",
    "pretty_colonial_borders.txt",
    "sevencities.txt",
    "siberiancolonization.txt",
    "sunsetinvasion.txt",
    "tradecompanyevents.txt",
}

HRE_FILES = {
    "freecities.txt",
    "holyromanempire.txt",
    "legatusnatus.txt",
    "pragmaticsanction.txt",
    "primasgermaniae.txt",
}

DYNASTIC_FILES = {
    "dynastic.txt",
    "electivemonarchy.txt",
    "haremevents.txt",
    "hispanicmonarchy.txt",
    "unionevents.txt",
    "womeninhistory.txt",
}

REVOLUTION_FILES = {
    "center_of_revolution_events.txt",
    "german_revolution_disaster_events.txt",
    "hungarian_revolution_disaster_events.txt",
    "revolutionaryempire.txt",
    "revrepublicfactions.txt",
}

OBSOLETE_SYSTEM_FILES = {
    "chineseempire.txt",
    "chinesefactions.txt",
    "dutchrepublic.txt",
    "empires.txt",
    "ger_events.txt",
    "greatbullionfamine.txt",
    "greatmen.txt",
    "industrialization.txt",
    "institutions.txt",
    "italianwars.txt",
    "japan.txt",
    "libirumveto.txt",
    "low_countries_events.txt",
    "mamlukevents.txt",
    "papalstate.txt",
    "persianinfluence.txt",
    "pricechanges.txt",
    "purple_phoenix_events.txt",
    "russianprincipalities.txt",
    "russiantsardom.txt",
    "salonikaevents.txt",
    "streltsy.txt",
    "tribalsuccession.txt",
    "usadlc.txt",
}

# These common/disasters files must be shadowed as well. Otherwise a removed
# historical event chain could leave a country trapped in a disaster whose
# start/end events no longer perform their original state changes.
KEEP_DISASTER_DEFINITIONS = {
    "civil_war.txt",
    "internal_conflicts.txt",
}


def locate_game(explicit: Path | None) -> Path:
    if explicit is not None:
        if not (explicit / "eu4.exe").exists():
            raise SystemExit(f"EU4 game root does not contain eu4.exe: {explicit}")
        return explicit
    for candidate in GAME_CANDIDATES:
        if (candidate / "eu4.exe").exists():
            return candidate
    raise SystemExit("Could not locate the EU4 installation; pass --game-root.")


def is_mission_event(filename: str) -> bool:
    name = filename.lower()
    return (
        "missionevents" in name
        or "mission_events" in name
        or "_mission_" in name
        or name.endswith("_missions.txt")
    )


def classify_event(filename: str) -> str | None:
    name = filename.lower()
    if "flavor" in name:
        return "country_flavor"
    if is_mission_event(name):
        return "mission_content"
    if name.startswith("disaster_") and name not in KEEP_DISASTER_EVENT_FILES:
        if "revolution" in name or name == "disaster_liberalism.txt":
            return "revolution_history"
        if "religious" in name:
            return "religious_wars"
        return "historical_disaster"
    if name.startswith("incident_"):
        return "hre_history"
    if name in RELIGIOUS_WAR_FILES:
        return "religious_wars"
    if name in COLONIAL_FILES:
        return "colonial_history"
    if name in HRE_FILES:
        return "hre_history"
    if name in DYNASTIC_FILES:
        return "dynastic_history"
    if name in REVOLUTION_FILES:
        return "revolution_history"
    if name in OBSOLETE_SYSTEM_FILES:
        return "obsolete_system"
    return None


def code_part(line: str) -> str:
    """Return a line without comments while respecting quoted # characters."""
    result: list[str] = []
    quoted = False
    escaped = False
    for char in line:
        if escaped:
            result.append(char)
            escaped = False
            continue
        if char == "\\" and quoted:
            result.append(char)
            escaped = True
            continue
        if char == '"':
            quoted = not quoted
            result.append(char)
            continue
        if char == "#" and not quoted:
            break
        result.append(char)
    return "".join(result)


def brace_delta(line: str) -> int:
    code = code_part(line)
    quoted = False
    escaped = False
    delta = 0
    for char in code:
        if escaped:
            escaped = False
        elif char == "\\" and quoted:
            escaped = True
        elif char == '"':
            quoted = not quoted
        elif not quoted and char == "{":
            delta += 1
        elif not quoted and char == "}":
            delta -= 1
    return delta


EVENT_START = re.compile(r"^\s*(country_event|province_event)\s*=\s*\{")
ID_LINE = re.compile(r"^\s*id\s*=\s*([^\s#]+)")
NAMESPACE_LINE = re.compile(r"^\s*namespace\s*=\s*([^\s#]+)")


def parse_event_definitions(text: str, source: Path) -> tuple[list[str], list[tuple[str, str]]]:
    namespaces: list[str] = []
    definitions: list[tuple[str, str]] = []
    lines = text.splitlines()
    index = 0
    while index < len(lines):
        code = code_part(lines[index])
        namespace_match = NAMESPACE_LINE.match(code)
        if namespace_match:
            namespace = namespace_match.group(1)
            if namespace not in namespaces:
                namespaces.append(namespace)
        start_match = EVENT_START.match(code)
        if not start_match:
            index += 1
            continue

        event_type = start_match.group(1)
        depth = brace_delta(code)
        event_id: str | None = None
        index += 1
        while index < len(lines) and depth > 0:
            current = code_part(lines[index])
            if depth == 1 and event_id is None:
                id_match = ID_LINE.match(current)
                if id_match:
                    event_id = id_match.group(1)
            depth += brace_delta(current)
            index += 1
        if depth != 0:
            raise ValueError(f"Unbalanced event block in {source}")
        if event_id is None:
            raise ValueError(f"Event without a top-level id in {source}")
        definitions.append((event_type, event_id))
    return namespaces, definitions


def disabled_event_text(source: Path, category: str) -> str:
    text = source.read_text(encoding="cp1252")
    namespaces, definitions = parse_event_definitions(text, source)
    lines = [
        MARKER,
        f"# Disabled vanilla file: {source.name}",
        f"# Category: {category} - {CATEGORY_REASONS[category]}",
        "# IDs are retained as hidden no-ops for vanilla on-action compatibility.",
        "",
    ]
    for namespace in namespaces:
        lines.extend([f"namespace = {namespace}", ""])
    for event_type, event_id in definitions:
        lines.extend(
            [
                f"{event_type} = {{",
                f"\tid = {event_id}",
                "\thidden = yes",
                "\tis_triggered_only = yes",
                "\ttitle = eu4_2k_disabled_event_title",
                "\tdesc = eu4_2k_disabled_event_desc",
                "\tpicture = DIPLOMACY_eventPicture",
                "\toption = { name = eu4_2k_disabled_event_option }",
                "}",
                "",
            ]
        )
    return "\n".join(lines)


def disabled_disaster_text(source: Path) -> str:
    return "\n".join(
        [
            MARKER,
            f"# Disabled vanilla disaster definitions: {source.name}",
            "# Its historical event chain is disabled for the 2000 scenario.",
            "",
        ]
    )


def expected_outputs(game: Path) -> tuple[dict[Path, str], Counter[str]]:
    outputs: dict[Path, str] = {}
    categories: Counter[str] = Counter()
    for source in sorted((game / "events").glob("*.txt"), key=lambda p: p.name.lower()):
        category = classify_event(source.name)
        if category is None:
            continue
        outputs[EVENT_OUTPUT / source.name] = disabled_event_text(source, category)
        categories[category] += 1

    for source in sorted((game / "common" / "disasters").glob("*.txt"), key=lambda p: p.name.lower()):
        if source.name.lower() in KEEP_DISASTER_DEFINITIONS or "estate_" in source.name.lower():
            continue
        outputs[DISASTER_OUTPUT / source.name] = disabled_disaster_text(source)
    return outputs, categories


def generated_files() -> set[Path]:
    found: set[Path] = set()
    for directory in (EVENT_OUTPUT, DISASTER_OUTPUT):
        if not directory.exists():
            continue
        for path in directory.glob("*.txt"):
            try:
                first_line = path.read_text(encoding="cp1252").splitlines()[0]
            except (IndexError, UnicodeDecodeError):
                continue
            if first_line == MARKER:
                found.add(path)
    return found


def generate(game: Path) -> Counter[str]:
    outputs, categories = expected_outputs(game)
    expected_paths = set(outputs)
    for stale in sorted(generated_files() - expected_paths):
        stale.unlink()
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="cp1252", newline="\n")
    LOCALISATION_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    LOCALISATION_OUTPUT.write_text(LOCALISATION_TEXT, encoding="utf-8-sig", newline="\n")
    return categories


def check(game: Path) -> Counter[str]:
    outputs, categories = expected_outputs(game)
    errors: list[str] = []
    for path, expected in outputs.items():
        if not path.exists():
            errors.append(f"missing generated override: {path.relative_to(ROOT)}")
        elif path.read_text(encoding="cp1252") != expected:
            errors.append(f"stale generated override: {path.relative_to(ROOT)}")
    for stale in sorted(generated_files() - set(outputs)):
        errors.append(f"unexpected generated override: {stale.relative_to(ROOT)}")
    if not LOCALISATION_OUTPUT.exists():
        errors.append(f"missing generated localization: {LOCALISATION_OUTPUT.relative_to(ROOT)}")
    elif LOCALISATION_OUTPUT.read_text(encoding="utf-8-sig") != LOCALISATION_TEXT:
        errors.append(f"stale generated localization: {LOCALISATION_OUTPUT.relative_to(ROOT)}")
    if errors:
        raise SystemExit("\n".join(errors))
    return categories


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", nargs="?", choices=("generate",), default="generate")
    parser.add_argument("--check", action="store_true", help="Validate without writing files.")
    parser.add_argument("--game-root", type=Path)
    args = parser.parse_args()
    game = locate_game(args.game_root)
    categories = check(game) if args.check else generate(game)
    verb = "Validated" if args.check else "Generated"
    total = sum(categories.values())
    detail = ", ".join(f"{key}={categories[key]}" for key in sorted(categories))
    print(f"{verb} {total} disabled vanilla event-file overrides ({detail}).")


if __name__ == "__main__":
    try:
        main()
    except ValueError as exc:
        print(exc, file=sys.stderr)
        raise SystemExit(1) from exc
